import assert from 'node:assert/strict';
import test from 'node:test';
import { type CodeSearchFileContent, type CodeSearchFileList, type CodeSearchFunctions, CodeSearchService, runCodeSearchBenchmark } from '../../../packages/runtime/src/hand/index.js';
import { CODE_SEARCH_CONTRACT_VERSION, CODE_SEARCH_SERVICE_ID, type CodeSearchRequest } from '../../../packages/contracts/src/index.js';

class FixtureFunctions implements CodeSearchFunctions {
  readonly reads: string[] = [];
  constructor(private readonly files: Readonly<Record<string, string>>, private readonly failedReads = new Set<string>()) {}
  async findFiles(input: Pick<CodeSearchRequest, 'workspaceRef' | 'path'>): Promise<CodeSearchFileList> { const prefix = input.path === '.' ? '' : `${input.path.replace(/\/$/, '')}/`; return { paths: Object.keys(this.files).filter((path) => path.startsWith(prefix)).sort(), complete: true, unresolvedPaths: [] }; }
  async readFile(input: { readonly workspaceRef: string; readonly path: string }): Promise<CodeSearchFileContent> { this.reads.push(input.path); if (this.failedReads.has(input.path)) throw new Error(`fixture read failed: ${input.path}`); const content = this.files[input.path]; if (content === undefined) throw new Error(`fixture file missing: ${input.path}`); return { path: input.path, content }; }
}
function request(overrides: Partial<CodeSearchRequest> = {}): CodeSearchRequest { return { serviceId: CODE_SEARCH_SERVICE_ID, contractVersion: CODE_SEARCH_CONTRACT_VERSION, workspaceRef: 'workspace://fixture', path: '.', query: 'needle', queryKind: 'literal', contextLines: 1, ...overrides }; }
function service(functions: CodeSearchFunctions): CodeSearchService { return new CodeSearchService({ functions }); }

test('code.search recursively searches files and returns complete evidence fields', async () => {
  const functions = new FixtureFunctions({ 'src/a.ts': 'before\nneedle here\nafter', 'src/b.ts': 'none', 'src/nested/c.ts': 'needle twice\nneedle again' });
  const report = await service(functions).execute(request({ path: 'src' }));
  assert.equal(report.status, 'succeeded'); assert.equal(report.searchComplete, true); assert.equal(report.filesDiscovered, 3); assert.equal(report.filesSearched, 3); assert.equal(report.matchesFound, 3);
  assert.deepEqual(report.matches.map((match) => `${match.path}:${match.line}`), ['src/a.ts:2', 'src/nested/c.ts:1', 'src/nested/c.ts:2']); assert.deepEqual(report.matches[0]?.contextBefore, ['before']); assert.deepEqual(report.matches[0]?.contextAfter, ['after']); assert.deepEqual(functions.reads, ['src/a.ts', 'src/b.ts', 'src/nested/c.ts']);
});
test('code.search distinguishes symbol matches from substring matches', async () => { const report = await service(new FixtureFunctions({ 'src/a.ts': 'foobar\nfoo\nfooBar' })).execute(request({ query: 'foo', queryKind: 'symbol' })); assert.equal(report.status, 'succeeded'); assert.equal(report.matchesFound, 1); assert.equal(report.matches[0]?.line, 2); });
test('code.search reports a bounded result set without lying about total matches', async () => { const report = await service(new FixtureFunctions({ 'a.ts': 'needle\nneedle', 'b.ts': 'needle' })).execute(request({ maxResults: 2 })); assert.equal(report.status, 'succeeded'); assert.equal(report.matchesFound, 3); assert.equal(report.matches.length, 2); assert.equal(report.resultsTruncated, true); assert.equal(report.searchComplete, true); });
test('code.search returns partial success and strict failure distinctly when a file cannot be read', async () => { const functions = new FixtureFunctions({ 'ok.ts': 'needle', 'broken.ts': 'needle' }, new Set(['broken.ts'])); const partial = await service(functions).execute(request()); assert.equal(partial.status, 'succeeded'); assert.equal(partial.searchComplete, false); assert.deepEqual(partial.unresolvedPaths, ['broken.ts']); assert.equal(partial.matchesFound, 1); const strict = await service(functions).execute(request({ requireComplete: true })); assert.equal(strict.status, 'failed'); assert.equal(strict.failure?.code, 'search-incomplete'); assert.equal(strict.searchComplete, false); assert.deepEqual(strict.unresolvedPaths, ['broken.ts']); });
test('code.search invalid scope is a stable structured failure', async () => { const report = await service(new FixtureFunctions({})).execute(request({ path: '../outside' })); assert.equal(report.status, 'failed'); assert.equal(report.failure?.code, 'invalid-request'); assert.equal(report.summary, 'search path must stay inside the workspace'); assert.equal(report.unresolvedPaths.length, 0); });
test('code.search invalid regex is returned as a report instead of escaping the service contract', async () => { const report = await service(new FixtureFunctions({ 'src/a.ts': 'needle' })).execute(request({ query: '[', queryKind: 'regex' })); assert.equal(report.status, 'failed'); assert.equal(report.failure?.code, 'invalid-request'); assert.equal(report.summary, 'invalid search expression'); });
test('code.search benchmark is the reusable self-check for the public service contract', async () => { const result = await runCodeSearchBenchmark(service(new FixtureFunctions({ 'src/a.ts': 'needle', 'src/b.ts': 'other' })), [{ caseId: 'complete-hit', request: request({ path: 'src' }), assert: (report) => report.status === 'succeeded' && report.searchComplete && report.matchesFound === 1 ? [] : ['complete hit failed'] }, { caseId: 'complete-miss', request: request({ path: 'src', query: 'missing' }), assert: (report) => report.status === 'succeeded' && report.searchComplete && report.matchesFound === 0 ? [] : ['complete miss failed'] }]); assert.equal(result.total, 2); assert.equal(result.passed, 2); assert.equal(result.failed, 0); assert.ok(result.totalDurationMs >= 0); assert.ok(result.cases.every((item) => item.durationMs >= 0)); });
